engines/admin_app/config/routes.rb
AdminApp::Engine.routes.draw do
  mount AdminApp::Application => '/api', as: :api

  devise_for :admins,
    skip: %w(sessions registrations unlocks),
    class_name: 'AdminApp::Admin'

  as :admin do
    get 'login' => 'admin/sessions#new', as: :new_admin_session
    post 'login' => 'admin/sessions#create', as: :admin_session
    delete 'logout' => 'admin/sessions#destroy', as: :destroy_admin_session
  end

  root to: 'welcome#index'

  resources :admins, except: [:show]
  resources :users, except: [:show]
end

engines/admin_app/app/models/admin_app/admin.rb
# == Schema Information
#
# Table name: admin_app_admins
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#  first_name             :string
#  last_name              :string
#  role                   :string           default("admin")
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_admin_app_admins_on_email                 (email) UNIQUE
#  index_admin_app_admins_on_reset_password_token  (reset_password_token) UNIQUE
#  index_admin_app_admins_on_unlock_token          (unlock_token) UNIQUE
#

module AdminApp
  class Admin < ActiveRecord::Base
    extend Enumerize
    include Names

    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable, :recoverable, 
           :rememberable, :trackable, :validatable, :lockable

    enumerize :role, in: [:admin, :manager, :store_manager, :post_manager],
      default: :admin, predicates: true
  end
end

engines/admin_app/app/models/admin_app/user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  first_name             :string
#  last_name              :string
#  full_name              :string
#  role                   :string           default("admin")
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_admin_users_on_email                 (email) UNIQUE
#  index_admin_users_on_reset_password_token  (reset_password_token) UNIQUE
#

module AdminApp
  class User < ActiveRecord::Base
    self.table_name = 'admin_users'

    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
  end
end

engines/admin_app/app/controllers/admin_app/admin/sessions_controller.rb
module AdminApp
  class Admin::SessionsController < Devise::SessionsController
    layout 'admin_app/authentification'
  end
end

engines/admin_app/app/controllers/admin_app/admins_controller.rb
module AdminApp
  class AdminsController < AdminApp::BaseController
    def index
    end

    def new
    end

    def edit
    end

    def update
    end

    def destroy
    end
  end
end

engines/admin_app/app/controllers/admin_app/base_controller.rb
module AdminApp
  class BaseController < ActionController::Base
    layout 'admin_app/admin'
    before_action :authenticate_admin!
    # TODO add Admin::Pundit
    # include Pundit

    protected

    def authenticate_admin!
      if admin_signed_in?
        super
      else
        redirect_to new_admin_session_path
      end
    end
  end
end

engines/admin_app/app/controllers/admin_app/users_controller.rb
module AdminApp
  class UsersController < AdminApp::BaseController
    def index
    end

    def new
    end

    def edit
    end

    def update
    end

    def destroy
    end
  end
end

engines/admin_app/app/controllers/admin_app/welcome_controller.rb
module AdminApp
  class WelcomeController < AdminApp::BaseController
    def index
    end
  end
end

engines/admin_app/app/helpers/admin_app/admin_helper.rb
module AdminApp
  module AdminHelper
    def spinner size = 'fa-4x'
      content_tag :div, class: 'l-spinner' do
        content_tag :i, nil, class: ['fa fa-spinner fa-spin', size].join(' ')
      end
    end
  end
end

engines/admin_app/app/helpers/admin_app/sidebar_helper.rb
module AdminApp
  module SidebarHelper
    def sidebar_dropdown_link title
      link_to '#', default_sidebar_options do
        [
          content_tag(:span, title),
          content_tag(:span, nil, class: 'caret')
        ].join.html_safe
      end
    end

    private

    def default_sidebar_options
      {
        class: 'dropdown-toggle',
        data: {
          toggle: 'dropdown'
        },
        aria: {
          haspopup: true,
          expanded: false
        },
        role: 'button'
      }
    end
  end
end

engines/admin_app/app/views/admin_app/admins/index.html.haml
%h3= t 'admin.admins'

.l-justshop-admins
  = spinner

engines/admin_app/app/views/admin_app/shared/sidebar/_top_sidebar.html.haml
%nav.navbar-inverse.navbar.l-justshop-top-navigation
  %aside
    .navbar-header
      %button.navbar-toggle.collapsed{ data: { toggle: 'collapse', target: '#l-justshop-admin-collapse-navbar' }, 'aria-expanded' => 'false' }
        %span.sr-only
        - 3.times do
          %span.icon-bar
      - # TODO move it in global config
      = link_to 'JustShop', admin_app.root_path, class: 'navbar-brand'

    .collapse.navbar-collapse#l-justshop-admin-collapse-navbar
      %ul.nav.navbar-nav
        %li.dropdown
          = sidebar_dropdown_link t('admin.sidebar.users')
          %ul.dropdown-menu
            %li= link_to t('admin.sidebar.users'), admin_app.users_path
            %li= link_to t('admin.sidebar.admins'), admin_app.admins_path

      %ul.nav.navbar-nav.navbar-right
        %li= link_to t('admin.sidebar.logout'), destroy_admin_session_path, method: :delete

engines/admin_app/app/views/admin_app/users/index.html.haml
%h3= t 'admin.users'

.l-justshop-users
  = spinner

engines/admin_app/app/views/admin_app/welcome/index.html.haml
%h4 Welocme to the just shop admin side
= debug AdminApp::Admin.count
= debug current_admin

engines/admin_app/app/views/layouts/admin_app/admin.html.haml
!!!
%head(lang="#{I18n.locale}")
  %meta{ charset: 'utf-8' }
  %meta{ 'http-equiv' => 'X-UA-Compatible', content: 'IE=edge,chrome=1' }
  = csrf_meta_tags
  = include_gon init: true
  - # TODO move it in global config
  %title JustShop Admin
  = stylesheet_link_tag 'admin_app/admin'

%body.l-main-admin
  .l-header-sidebar= render 'admin_app/shared/sidebar/top_sidebar'
  .l-body
    .b-body
      = yield

  = javascript_include_tag 'admin_app/admin'
  = yield :javascripts

engines/admin_app/app/views/layouts/admin_app/authentification.html.haml
!!!
%head(lang="#{I18n.locale}")
  %meta{ charset: 'utf-8' }
  %meta{ 'http-equiv' => 'X-UA-Compatible', content: 'IE=edge,chrome=1' }
  = csrf_meta_tags
  = include_gon init: true
  %title Auth JustShop Admin
  = stylesheet_link_tag 'admin_app/authentification'

%body.l-authentification
  .l-header-sidebar
  .l-body
    .b-body
      .b-vertical-align-middle
      = yield

  = javascript_include_tag 'admin_app/authentification'
  = yield :javascripts